### ISSUE TITLE
Adposition as dependent of acl relation

### ISSUE THREAD

**Issue by hschoi4** [UniversalDependencies/UD_Chinese-GSD#4]
We noticed an inconsistency concerning the `acl` relation.
In 59% of the constructions involving an `acl` relation, the dependent is an adposition, which is not consistent with the guidelines. According to `acl` Chinese documentation, postnominal clausal modifiers are headed by the verb of the clause, which should be the dependent of the relation.

Adpositions concerned are mostly postpositions. Looking at the sentences, it seems like the adposition is not involved in a clausal modifiers. The `case` relation would therefore be more appropriate.

| Corpus         | # sentences | acl_adp | acl_non_adp | Total | % acl_adp | % acl_non_adp |
|----------------|------------:|--------:|------------:|------:|----------:|--------------:|
| UD_Chinese-GSD |        4997 |    1131 |         778 |  1909 |     59.24 |         40.75 |

We used [Grew](https://grew.fr/) tool to obtain the results.

**Comment by KoichiYasuoka** [comment]
Well @qipeng I've just made PR https://github.com/UniversalDependencies/UD_Chinese-GSDSimp/pull/7 first, and we will re-sync UD_Chinese-GSD.

**Comment by qipeng** [comment]
Fixed in #6 and similarly for Chinese-GSDSimp in https://github.com/UniversalDependencies/UD_Chinese-GSDSimp/pull/8.
